# Generated by Django 5.2.8 on 2025-12-02 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('exercise_type', models.CharField(choices=[('mcq', 'Múltipla escolha'), ('gap', 'Preencher lacuna'), ('translate', 'Tradução')], max_length=20)),
                ('choices', models.JSONField(blank=True, help_text='Lista de escolhas para MCQ', null=True)),
                ('answer', models.TextField()),
                ('level', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_shared', models.BooleanField(default=False, help_text='Se marcado, exercício é disponível para todos os usuários')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
